version: '3.7'
services:
  web:
    image: sunnywalden/yanagishima
    container_name: yanagishima
    volumes:
      - conf/yanagishima.properties:/opt/yanagishima/conf/yanagishima.properties
    ports:
      - "8899:8899"
    networks:
      - yanagishima
    restart: always

networks:
  yanagishima:
    driver: bridge